<p>
    This is basic Zend Framework example with fallowing features.
    <ul>
        <li>user registration</li>
        <li>users administration</li>
        <li>basic ACL</li>
    </ul>
    
    To login as admin use:
    <ul>
        <li>username: admin@admin.com</li>
        <li>password: admin@admin.com</li>
    </ul>
    
    <a href="https://github.com/janar/zfw-basic-example">Fork it @ Github</a>
</p>