<p><a href="<?php echo $this->url(array('controller'=>'users',
    'action'=>'add'));?>">Add new user</a></p>
<table id="admin-users">
<tr>
    <th>Email</th>
    <th>Name</th>
    <th>&nbsp;</th>
</tr>
    <?php foreach($this->users as $user){ ?>
        <tr>
            <td><?php echo $this->escape($user->email);?></td>
            <td><?php echo $this->escape($user->firstname . ' ' . $user->lastname); ?></td>
            <td>
                <a href="<?php echo $this->url(array('controller'=>'users',
                    'action'=>'edit', 'id'=>$user->id));?>">Edit</a>
                <a href="<?php echo $this->url(array('controller'=>'users',
                    'action'=>'delete', 'id'=>$user->id));?>">Delete</a>
            </td>
        </tr>
    <?php } ?>
</table>